name: Check CDN
on: 
#    schedule:
#      - cron: '1 6 * * *'
    workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: ./_action_files/check_js.sh
